### ISSUE TITLE
OCH Mind Dump

### ISSUE THREAD

**Issue by platten** [Project-Voltron/voltron#36]
## Discuss:
- Requirements
- Users / Data Consumers
- Query API
- Startup configuration and supported scopes
- Storage backend

**Comment by michalgorski84** [comment]
### Business case & context

### Buzz words

### Sub-tasks

### Context and prerequisite definition

### Out of scope

### Acceptance criteria

### Quality

**Comment by platten** [comment]
![OCH.png](https://images.zenhubusercontent.com/5efb8b84bf9ea08a79601728/74e346b4-6e57-4186-a44a-33423fbec83e)
