### ISSUE TITLE
Architecture Spike

### ISSUE THREAD

**Issue by jinoojain** [Project-Voltron/voltron#37]
To be researched, discussed, and decided upon: 
- [x] the scope of the architecture that will be documented as part of this spike
- [x] the approaches selected for implementing the various components
- [x] the tasks needed to complete the architecture
- [x] the sequence of tasks to be worked on, including dependencies
- [x] estimation of the size of each of the tasks

The artifact of this spike: 
- [x] documentation which outlines:
    - [x] the scope of the architecture that will be worked on in this next sprint
    - [x] a list of the tasks that need to be done (this list will be broken down into stories)

**Comment by pkosiec** [comment]
We identified the following tasks to do:

- Prepare sequence diagram
    - include all components to see E2E flow
    - base on a use case with the highest priority (e.g. installing application with dependencies)
    - validate current OCH database graph diagram (-> graph expert)

- Investigate Argo workflows
    - nested workflows
    - artifacts
    - passing input/output
    - conditions
    - context

- Figure out what, when and where to store configs (blocked by Investigate Argo workflows)
    - Kubernetes CRs vs DB (e.g. PostgreSQL) vs OCH

- Identify and prepare base runners schema:
   - e.g. Kubernetes Job runner, Helm3, Argo Workflow runner?

**Comment by jinoojain** [comment]
two items: 
- [ ] need use cases
- [ ] need validation from a graph expert (dgraph?)

**Comment by jinoojain** [comment]
Use cases document: https://docs.google.com/document/d/1QZdwasguB8Ho6lJgBYmj3EpQF9GGJTK2IE-h6buM5ls/edit?usp=sharing
