### ISSUE TITLE
Prepare sequence diagram

### ISSUE THREAD

**Issue by jinoojain** [Project-Voltron/voltron#38]
- [ ] Include all components to see E2E flow
- [ ] Base it on a use case with the highest priority (e.g. installing an application with dependencies)
  - [Use case document](https://docs.google.com/document/d/1QZdwasguB8Ho6lJgBYmj3EpQF9GGJTK2IE-h6buM5ls/edit?usp=sharing)
- [ ] Validate the current OCH database graph diagram with a graph expert

**Comment by mszostok** [comment]
Today we worked on a sequence diagram, it is in early stage available [here](https://drive.google.com/file/d/1eQfe_eLt4Hd9_ZvUiS03KE9jiurQunK5/view?usp=sharing)

We had a discussion with Paul regarding the action categorization, storing configs and modifying them. In addition, we need to support the upward and downward actions e.g. 
1. In the system, we have a mysql instance
2. During WP installation we attach to that instance
3. As a result of that installation we have a new hook added to that mysql instance. When mysql is modified(e.g. version upgrade), then the given webhook needs to be executed 

We need to take a look on the OAM model, especially Traits. 

New requirements:
-  supports registering webhooks for instances that are reused by other parts

**Comment by mszostok** [comment]
Today we finished the [High-level E2E Sequence diagram](https://drive.google.com/file/d/1i1rJsrodiEqoGwS9w2J9lYMolO4Q92En/view?usp=sharing) for the example Wordpress installation. 

As a part of the brainstorming during the creation of the e2e sequence diagram we define the way how to template the workflows in a generic way and described that in [Execution section](https://docs.google.com/document/d/1ud7xL3bXxEXtVPE8daA_DHYacKHMkn_jx6s7eaVT-NA/edit#heading=h.15n4qb68eps6) in OCF Draft.


Both things were discussed with Paul, and we have a common agreement regarding the workflows and e2e sequence diagram.

**Comment by pkosiec** [comment]
As a part of detailed sequence diagrams we have to do the following things:
- Submitting OCF manifest to OCH (validation, signature, promotion to envs)
- Resolving dependencies: API calls to OCH
- Run kubebench from SDK
- Sequence diagram with Knative Eventing/OpenFaaS runner (open question: should we support CloudEvents?)

**Comment by mszostok** [comment]
Today Paweł started working on the example for running the kubebench project using SDK. From that we will create the sequence diagram. We had a sync about the approach that we want to take. It will be inspired by the https://github.com/99designs/gqlgen.

**Comment by pkosiec** [comment]
Today I continued working on the Kubebench example. However, the example is still not finished. Also, we haven't discussed it yet with Mateusz.
Here's the code: https://github.com/Project-Voltron/scratchpad/tree/sdk-example

**Comment by pkosiec** [comment]
Today I finalized examples, however still I didn't consult the ideas with Mateusz, as we parked this topic for coming up with labeling concept. The code is located here: https://github.com/Project-Voltron/scratchpad/tree/sdk-example

**Comment by pkosiec** [comment]
Along with Mateusz we discussed the examples. Generally we would like to extend the level of the detail for some SDK methods, to describe how it works fully. We put TODO comments in the code and parked the topic to focus on types extension, abstract and concrete types and labeling/tagging concept.

Code is still located in the same branch.

**Comment by pkosiec** [comment]
We didn't have time today to focus on the task. Anyway, we discussed it for a few moments and we came across one challenge regarding SDK example:
For running Kubebench we have to set PID to "host". Currently we have just the OCI image details in the OCI Image runner (from OCI image spec) and we are missing OCI Runtime properties (from OCI runtime spec), which contains e.g. required PID property.

For now we renamed OCIImage struct to OCI and put Image and Runtime properties underneath, to enable users to configure OCI runtime as well.

**Comment by pkosiec** [comment]
Today we finished and presented Go SDK example for running kubebench. There are two approaches showed in the PR: static (with static code generation) and dynamic. This part is ready to review.

Here's the link to pull request: https://github.com/Project-Voltron/scratchpad/pull/9
