### ISSUE TITLE
Familiarization with Runners (Argo, KNative)

### ISSUE THREAD

**Issue by jinoojain** [Project-Voltron/voltron#39]
1-day timebox to get familiar with Argo/KNative

**Comment by pkosiec** [comment]
I spend a couple of hours today on the Argo familiarization. I played around with Argo on a local Minikube cluster.

I found pretty good articles how Argo implemented artifacts:
https://blog.argoproj.io/artifacts-management-in-container-native-workflows-part-1-f6efa838666b
https://blog.argoproj.io/artifacts-management-in-container-native-workflows-part-2-30105e513883

I came up with one idea: on MVP we could use Argo as a built-in Runner. In other words, even Helm runner could be implemented on top of Argo built-in Runner. So helm install action would be represented by Argo workflow with just a single step. Obviously, that means Argo has to be shipped with Voltron, at least in MVP state.

In this way we could get the artifacts-related logic for free. One thing we need is to configure Argo with Minio/external S3 to enable artifacts support. Then we could store Instances in the minio itself, and reference them (or copy them if needed) to our database.
