### ISSUE TITLE
Investigate Runners

### ISSUE THREAD

**Issue by jinoojain** [Project-Voltron/voltron#40]
- Built-in OCI Image runner -> how to treat it equally across external OCH repositories? How to distinguish it from other runners
  - Cap.vendor.projectvoltron.dev.type.runner.builtin.run
  - Possible solutions:
    - builtin runner as another property of `action` or entry under spec `OCIImage` with own fields?
    - Core read-only, OCH is compiled with core and it cannot be modified; Implementation of built-in runner is built-in into the workflow engine (as a plugin?)
    - For vendor repos: validating type.builtin.runner.oci-image schema before running it
  - Describe E2e flow:
    - Where the schema for OCI Image runner is defined 
    - Who and where implements the OCI Image converters 
    - How the is executed conversion between OCI Image runner schema to concrete type (e.g. from generic OCI image definition to Argo container manifest)
- How to pass the input and output parameters between steps in workflow. We need that information to finish the concept for OCF Runners
- We want to define what the instance is. How and when to store the artifacts
- Prepare schema & update the OCF draft
- Passing context (during template render?)
- Passing user input
  - Possible solution: Via context and passing it during template render

---------
Old:
- Artifacts
- Passing input/output
- Conditions
- Context
- Rollback?
- Discussion with Paul on solutions (& iteration?)
- Ensure OCF documentation is up to date

**Comment by pkosiec** [comment]
Few things we have to brainstorm and discuss during this task:
- porter runner with mixins (like Helm... Knative? Argo?)
- runner lifecycle (install/upgrade/uninstall)?
