### ISSUE TITLE
Storing configs - what/when/where

### ISSUE THREAD

**Issue by jinoojain** [Project-Voltron/voltron#41]
- Kubernetes CRs vs. DB (PostgreSQL) vs. OCH
- Artifact: diagram/architecture to describe the pros/cons of different methods
- TBD: making a decision on the path forward?
- Ensure OCF documentation is up to date

**Comment by pkosiec** [comment]
In PR #3, @platten suggested an idea to define config as a third schema parameter for Interface:
> Basically something which represents the configuration of this object which should be persisted to the configuration registry. The config schema is not the output, as the output may have an error or additional unnecessary information.

We should consider it during the task investigation.
