### ISSUE TITLE
Master skeleton of architecture

### ISSUE THREAD

**Issue by jinoojain** [Project-Voltron/voltron#44]
Living document that includes: 
- Functional requirements
- Architecture
- Interfaces
- Project task breakdowns
- List of assumptions/learnings/decisions
- Changelog of components

[link GH issues where applicable under each section for WIP]

**Comment by pkosiec** [comment]
Today we started to work on the document. Current draft is available here: https://docs.google.com/document/d/1LRwS_r_IyObtVVnWssGq9MdgFeV-GXZ_r3U3uetzt9E/edit

After meeting with Paul regarding labelling (and platform/envs), I addressed some OCF Draft commends from review.

**Comment by mszostok** [comment]
Today Paweł started working on the example for running the kubebench project using SDK. From that we will create the sequence diagram. We had a sync about the approach that we want to take. It will be inspired by the https://github.com/99designs/gqlgen.

**Comment by mszostok** [comment]
Today we finished the initial document and now it is ready for review.

Today we also worked on finishing fixing the OCF draft document after Paul review.

**Comment by pkosiec** [comment]
Today we resolved review comments in the architecture doc and almost all of them from the OCF draft.

In the OCF draft, after review, there are two comments left regarding versioning:
- where will the user go to find out which versions are deprecated
- OCH upgrade/downgrade

**Comment by mszostok** [comment]
Today we finished answering all the comments in master architecture, on Monday we discuss with Paul the rest two comments that are still an open topic.
